package com.starsep.puzzles

data class Puzzle(val nameId: Int)

val Puzzles = listOf(
    Puzzle(R.string.name_blackbox),
    Puzzle(R.string.name_bridges),
    Puzzle(R.string.name_cube),
    Puzzle(R.string.name_dominosa),
    Puzzle(R.string.name_fifteen),
    Puzzle(R.string.name_filling),
    Puzzle(R.string.name_flip),
    Puzzle(R.string.name_flood),
    Puzzle(R.string.name_galaxies),
    Puzzle(R.string.name_guess),
    Puzzle(R.string.name_inertia),
    Puzzle(R.string.name_keen),
    Puzzle(R.string.name_lightup),
    Puzzle(R.string.name_loopy),
    Puzzle(R.string.name_magnets),
    Puzzle(R.string.name_map),
    Puzzle(R.string.name_mines),
    Puzzle(R.string.name_net),
    Puzzle(R.string.name_netslide),
    Puzzle(R.string.name_palisade),
    Puzzle(R.string.name_pattern),
    Puzzle(R.string.name_pearl),
    Puzzle(R.string.name_pegs),
    Puzzle(R.string.name_range),
    Puzzle(R.string.name_rect),
    Puzzle(R.string.name_samegame),
    Puzzle(R.string.name_signpost),
    Puzzle(R.string.name_singles),
    Puzzle(R.string.name_sixteen),
    Puzzle(R.string.name_slant),
    Puzzle(R.string.name_solo),
    Puzzle(R.string.name_tents),
    Puzzle(R.string.name_towers),
    Puzzle(R.string.name_tracks),
    Puzzle(R.string.name_twiddle),
    Puzzle(R.string.name_undead),
    Puzzle(R.string.name_unequal),
    Puzzle(R.string.name_unruly),
    Puzzle(R.string.name_untangle),
)